### ISSUE TITLE
"Template" directory missing for Adminhtml

### ISSUE THREAD

**Issue by ravioztek** [E-ComProcessing/magento-ce-ecp-plugin#1]
File structure for admin design given as "app/design/adminhtml/default/default/ecomprocessing" instead of "app/design/adminhtml/default/default/template/ecomprocessing".

Please fix this.

**Comment by ghost** [comment]
Hello, we've pushed a new version - [`1.2.4`](https://github.com/E-ComProcessing/magento-ce-ecp-plugin/releases/tag/1.2.4) that fixes the reported issue.

Thank you for your submission
