### ISSUE TITLE
After enable payment method on checkout page payment method not found.

### ISSUE THREAD

**Issue by kishansiliconinfo** [E-ComProcessing/magento-ce-ecp-plugin#2]
System.log
<pre>2016-11-21T09:52:46+00:00 ERR (3): Warning: include(Genesis\Genesis.php): failed to open stream: No such file or directory  in /../magento/lib/Varien/Autoload.php on line 94</pre>
<b>Version : </b>Magento 1.9.2.3
<b>Question : </b>can you write down the directory structure of lib/Genesis/??

**Comment by dimitrovv** [comment]
Hi,

perhaps there is a problem loading our Gateway Client Library using ```composer```.

Please try to replace the function __initLibrary__ in the __DataHelper__ Class:
https://github.com/E-ComProcessing/magento-ce-ecp-plugin/blob/master/app/code/community/EComProcessing/Genesis/Helper/Data.php#L32

```php
public function initLibrary()
    {
        // Mitigate PHP Bug #52339, as Magento already registers their AutoLoader
        if (!class_exists('\Genesis\Genesis', false)) {
             $genesisAutoLoadParams = array(
                'magento_root'                       => MAGENTO_ROOT,
                'integrated_genesis_lib_auto_loader' => Mage::getBaseDir('lib') . DS . 'Genesis' . DS . 'vendor' . DS . 'autoload.php',
                'genesis_composer_dir'               => 'genesisgateway',
                'check_genesis_lib_version'          => '1',
                'required_genesis_lib_version'       => ">= 1.4"
             );
             
             $genesisAutoLoadVarienObj = new Varien_Object($genesisAutoLoadParams);
             
             /* This Event will be handled from Observer EComProcessing_Genesis_Observer_GenesisAutoLoader (defined in etc/config.xml) */
             Mage::dispatchEvent('ecomprocessing_genesis_init_library', array('genesis_auto_load_params' => $genesisAutoLoadVarienObj));
        }     	 
    }
```

with this one

```php
public function initLibrary()
    {
        if (!class_exists('\Genesis\Genesis', false)) {
            include Mage::getBaseDir('lib') . DS . 'Genesis' . DS . 'vendor' . DS . 'autoload.php';
        }
    }
```

Best Regards,
Ventsislav Dimitrov

Web Developer

**Comment by kishansiliconinfo** [comment]
same issue..
unix system and the file system is case senstive issue i think so.

**Comment by kishansiliconinfo** [comment]
<b>Full system,log below :</b>
<pre>2016-11-21T11:39:02+00:00 ERR (3): Warning: include(/opt/lampp/htdocs/demo/includes/src/Genesis\Genesis.php): failed to open stream: No such file or directory  in /opt/lampp/htdocs/demo/includes/src/Varien_Autoload.php on line 94
2016-11-21T11:39:02+00:00 ERR (3): Warning: include(): Failed opening '/opt/lampp/htdocs/demo/includes/src/Genesis\Genesis.php' for inclusion (include_path='/opt/lampp/htdocs/demo/includes/src:.:/opt/lampp/lib/php')  in /opt/lampp/htdocs/demo/includes/src/Varien_Autoload.php on line 94
2016-11-21T11:39:02+00:00 ERR (3): Warning: include(/opt/lampp/htdocs/demo/includes/src/Genesis\Genesis.php): failed to open stream: No such file or directory  in /opt/lampp/htdocs/demo/includes/src/Varien_Autoload.php on line 94
2016-11-21T11:39:02+00:00 ERR (3): Warning: include(): Failed opening '/opt/lampp/htdocs/demo/includes/src/Genesis\Genesis.php' for inclusion (include_path='/opt/lampp/htdocs/demo/includes/src:.:/opt/lampp/lib/php')  in /opt/lampp/htdocs/demo/includes/src/Varien_Autoload.php on line 94
</pre>
If you need more info let me know.

**Comment by kishansiliconinfo** [comment]
Thanks it's working after i have deleted all generated cache but still have another issue can i close this issue and generate new one?
