### ISSUE TITLE
Payment method not found.

### ISSUE THREAD

**Issue by kishansiliconinfo** [E-ComProcessing/magento-ce-ecp-plugin#3]
After enable E-ComProcessing Direct with : 
Token : xxxxxxx
Username : xxxxxxx
Password : xxxxxxx
Test Mode : Yes
Transaction Type : Authorize
 New Order Status : pending
Payment from Applicable Countries : All Allowed countries
Minimum Order Total : 1
Maximum Order Total : 9999

<b>Error</b> : On checkout product it's say No Payment Methods.

**Comment by dimitrovv** [comment]
Hi,

this Payment Method requires SSL to be enabled on your **Frontend** and **Backend**.
Go to ```System``` -> ```Configuration``` -> ```General``` -> ```Web```
and enable SSL. 
You can find the ```Direct Payment Method``` requirements in the [Module Requirements Section](https://github.com/E-ComProcessing/magento-ce-ecp-plugin#requirements) in this Repository.

If you have already installed the required [PHP Extension](https://github.com/E-ComProcessing/magento-ce-ecp-plugin#genesisphp-requirements) mentioned in the [GitHub Repository](https://github.com/E-ComProcessing/magento-ce-ecp-plugin),
the payment method should get displayed on the Checkout Page.

--------------------------------
Best Regards,
Ventsislav Dimitrov

Web Developer

**Comment by kishansiliconinfo** [comment]
Is work on local environment ? after enable SSL frontend,backend payment method does not appear on checkout page.

**Comment by dimitrovv** [comment]
Hi,

change the **Secure Base Url** and **Unsecure Base Url** in **General** -> **Web Settings** to ```https://YOUR-SITE-DOMAIN/```
and create a **permanent** Redirect from ```http``` to ```https``` in your **VirtualHost**.

You could have a look at the **Magento** **isCurrentlySecure** function, which we use to determine if the **SSL** is enabled on your **WebSite**.
```app``` -> ```code``` -> ```core``` -> ```Mage``` -> ```Core``` -> ```Model``` -> ```Store.php``` -> ```function isCurrentlySecure```

**Comment by kishansiliconinfo** [comment]
Thanks for the support working can you please update README.md. guide will help you other developer who install this extension.

**Comment by dimitrovv** [comment]
Hi,

we will include the **SSL configuration Steps** in the ```README.md``` for the next version.

Thanks!
