### ISSUE TITLE
Transaction declined

### ISSUE THREAD

**Issue by kishansiliconinfo** [E-ComProcessing/magento-ce-ecp-plugin#4]
On response : {"success":false,"error":true,"error_messages":"Message: Transaction declined, please contact support
!\nDetails: Undefined error."}

Test Mode : yes

exception.log
<pre>
2016-11-22T13:09:06+00:00 ERR (3): 
exception 'Genesis\Exceptions\ErrorAPI' with message 'Message: Transaction declined, please contact support!
Details: Undefined error.' in /opt/lampp/htdocs/magento/lib/Genesis/src/Genesis/API/Response.php:106
Stack trace:
#0 /opt/lampp/htdocs/magento/lib/Genesis/src/Genesis/Genesis.php(128): Genesis\API\Response->parseResponse('<?xml version="...')
#1 /opt/lampp/htdocs/magento/app/code/community/EComProcessing/Genesis/Model/Direct.php(316): Genesis\Genesis->execute()
#2 /opt/lampp/htdocs/magento/app/code/community/EComProcessing/Genesis/Model/Direct.php(134): EComProcessing_Genesis_Model_Direct->_authorize3d(Object(Mage_Sales_Model_Order_Payment), 105)
#3 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): EComProcessing_Genesis_Model_Direct->authorize(Object(Mage_Sales_Model_Order_Payment), 105)
#4 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 105)
#5 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#6 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#7 [internal function]: Mage_Sales_Model_Order->place()
#8 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#9 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#10 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#11 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#12 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#13 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#14 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#15 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#16 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#17 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#18 /opt/lampp/htdocs/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#19 /opt/lampp/htdocs/magento/index.php(83): Mage::run('', 'store')
#20 {main}
2016-11-22T13:09:06+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Message: Transaction declined, please contact support!
Details: Undefined error.' in /opt/lampp/htdocs/magento/app/Mage.php:595
Stack trace:
#0 /opt/lampp/htdocs/magento/app/code/community/EComProcessing/Genesis/Model/Direct.php(355): Mage::throwException('Message: Transa...')
#1 /opt/lampp/htdocs/magento/app/code/community/EComProcessing/Genesis/Model/Direct.php(134): EComProcessing_Genesis_Model_Direct->_authorize3d(Object(Mage_Sales_Model_Order_Payment), 105)
#2 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(1089): EComProcessing_Genesis_Model_Direct->authorize(Object(Mage_Sales_Model_Order_Payment), 105)
#3 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order/Payment.php(342): Mage_Sales_Model_Order_Payment->_authorize(true, 105)
#4 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#5 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#6 [internal function]: Mage_Sales_Model_Order->place()
#7 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(105): call_user_func(Array)
#8 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#9 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#10 /opt/lampp/htdocs/magento/app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#11 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/Model/Type/Onepage.php(812): Mage_Sales_Model_Service_Quote->submitAll()
#12 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(579): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#14 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#15 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#17 /opt/lampp/htdocs/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#18 /opt/lampp/htdocs/magento/index.php(83): Mage::run('', 'store')
#19 {main}
2016-11-22T13:09:06+00:00 ERR (3): 
exception 'Zend_Mail_Transport_Exception' with message 'Unable to send mail. ' in /opt/lampp/htdocs/magento/lib/Zend/Mail/Transport/Sendmail.php:137
Stack trace:
#0 /opt/lampp/htdocs/magento/lib/Zend/Mail/Transport/Abstract.php(348): Zend_Mail_Transport_Sendmail->_sendMail()
#1 /opt/lampp/htdocs/magento/lib/Zend/Mail.php(1194): Zend_Mail_Transport_Abstract->send(Object(Zend_Mail))
#2 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Email/Template.php(451): Zend_Mail->send()
#3 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/Email/Template.php(508): Mage_Core_Model_Email_Template->send('owner@example.c...', 'Owner', Array)
#4 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/Helper/Data.php(247): Mage_Core_Model_Email_Template->sendTransactional('checkout_paymen...', 'general', 'owner@example.c...', 'Owner', Array)
#5 /opt/lampp/htdocs/magento/app/code/core/Mage/Checkout/controllers/OnepageController.php(596): Mage_Checkout_Helper_Data->sendPaymentFailedEmail(Object(Mage_Sales_Model_Quote), 'Message: Transa...')
#6 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_OnepageController->saveOrderAction()
#7 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#8 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /opt/lampp/htdocs/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#10 /opt/lampp/htdocs/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /opt/lampp/htdocs/magento/index.php(83): Mage::run('', 'store')
#12 {main}
</pre>

system.log
<pre>
2016-11-22T13:09:05+00:00 DEBUG (7): Authorize 3D-Secure transaction for order #100000001
</pre>

**Comment by dimitrovv** [comment]
Hi,

your **IP address** is not whilelisted in our **Gateway**.
Please contact our [Tech Support Team](mailto:Tech-Support@e-comprocessing.com)
to fix this issue.

---------------
Best Regards,
Ventsi

**Comment by kishansiliconinfo** [comment]
Can you give me official site and documentation link.

**Comment by dimitrovv** [comment]
Hi,

you should have received your credentials for our staging (Test) environment from our Tech Support.
They will be able to whitelist your IP in order to send API Requests.
